apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: infra-lets-encrypt-cluster-issuer-staging
spec:
  acme:
    email: <email>
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: infra-lets-encrypt-cluster-issuer-staging-private-key
    solvers:
      - http01:
          ingress:
            class: nginx